set(CMAKE_SYSTEM_NAME      Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(TOOLCHAIN_PREFIX arm-none-eabi-)
set(CPU_FLAGS "-mcpu=cortex-m4 -mthumb -mfloat-abi=hard")

set(CMAKE_C_COMPILER     ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_C_FLAGS_INIT   "${CPU_FLAGS}")

set(CMAKE_CXX_COMPILER   ${TOOLCHAIN_PREFIX}g++)
set(CMAKE_CXX_FLAGS_INIT "${CPU_FLAGS}")

set(CMAKE_ASM_COMPILER   ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_ASM_FLAGS_INIT "${CPU_FLAGS} -x assembler-with-cpp")

set(CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}objcopy)
set(CMAKE_SIZE    ${TOOLCHAIN_PREFIX}size)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
